version: '3'

services:
  client-db:
    image: michisig/tt-client-db:${version}
    container_name: client-db
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  client-service:
    image: michisig/tt-client-service:${version}
    container_name: client-service
    ports:
      - "8081:8081"
    healthcheck:
      test: "curl http://localhost:8081/internal/readiness"
      interval: 3s
      timeout: 5s
      retries: 5
    depends_on:
      client-db:
        condition: service_healthy