spring:
  main:
    web-application-type: none
    banner-mode: off

armeria:
  ports:
    - port: 8081

logging:
  config: classpath:logback-local.xml

cors:
  origins: 'http://localhost:5173'
  methods: GET, POST, PUT, DELETE
  maxAgeSeconds: 3600

persistence:
  dialect: H2

rate-limiter:
  services:
    ValidateRestClientServiceDecorator:
      - method: findAll
        limit: 2000
      - method: findByEntityId
        limit: 2000
      - method: save
        limit: 2000