spring:
  main:
    web-application-type: none
    banner-mode: off

armeria:
  ports:
    - port: 8081
      protocols:
        - HTTP

logging:
  config: classpath:logback-local.xml

persistence:
  dialect: POSTGRES
  url: jdbc:postgresql://localhost:5433/client
  schema: client
  username: client_appl
  password: qwe123
  maxPoolSize: 10